version: "3.9"

services:
  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: "redis://redis:6379"
      CORS_DOMAIN: "https://4rbanime.fun,https://4rabanime.com"
    expose:
      - "4040"
    networks: [web]
    labels:
      - "traefik.enable=true"
      # Remove prefix stripping since we're using exact path matching
      - "traefik.http.routers.proxy.rule=Host(`4rbanime.fun`,`4rabanime.com`) && Path(`/m3u8-proxy`)"  # Changed to exact path match
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=myresolver"
      - "traefik.http.services.proxy.loadbalancer.server.port=4040"

  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_URL: https://4rbanime.fun  # Keep base URL
    env_file:
      - .env.production
    expose:
      - "3000"
    networks: [web]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`4rbanime.fun`,`4rabanime.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  redis:
    image: redis:7-alpine
    networks: [web]

networks:
  web:
    external: true