version: "3.9"

services:
  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    # No published ports needed — Dokploy's Traefik will route 3000
    expose:
      - "3000"
    networks:
      - web

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: redis://redis:6379
      # Fixed CORS domains to match your actual domains
      CORS_DOMAIN: "https://4rabanime.com,https://4rbanime.fun"
    expose:
      - "4040"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      
      # —— CORS middleware ——
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Methods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Headers=Origin,Accept,Content-Type,Authorization"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Credentials=true"

      # —— Path stripping middleware ——
      - "traefik.http.middlewares.strip-proxy.stripprefix.prefixes=/m3u8-proxy"

      # 🔒 HTTPS router for m3u8-proxy
      - "traefik.http.routers.proxy.rule=Host(`4rabanime.com`,`4rbanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.middlewares=strip-proxy,proxy-cors"
      - "traefik.http.services.proxy.loadbalancer.server.port=4040"

      # HTTP redirect to HTTPS
      - "traefik.http.routers.proxy-http.rule=Host(`4rabanime.com`,`4rbanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy-http.entrypoints=web"
      - "traefik.http.routers.proxy-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

  redis:
    image: redis:7-alpine
    networks:
      - web

networks:
  web:
    external: true