version: "3.9"

services:
  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    # No published ports needed — Dokploy’s Traefik will route 3000
    expose:
      - "3000"
    networks:
      - web

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: redis://redis:6379
      CORS_DOMAIN: "https://4rabanime.com,https://4rabanime.fun"
    expose:
      - "4040"
    networks:
      - web

  redis:
    image: redis:7-alpine
    networks:
      - web

networks:
  web:
    driver: bridge
