version: "3.9"

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
      args:
        TARGETOS: linux
        TARGETARCH: amd64
    environment:
      PORT: 4040
      REDIS_URL: "redis://redis:6379"
      CORS_DOMAIN: "https://4rabanime.fun,https://4rbanime.com"
    expose:
      - "4040"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`4rabanime.fun`, `4rbanime.com`, `4rbanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy.priority=10"  # Higher priority than Next.js
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.tls.certresolver=myresolver"
      - "traefik.http.services.proxy.loadbalancer.server.port=4040"
      - "traefik.http.middlewares.strip-m3u8-prefix.stripprefix.prefixes=/m3u8-proxy"
      - "traefik.http.routers.proxy.middlewares=strip-m3u8-prefix"

  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    expose:
      - "3000"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`4rabanime.fun`, `4rbanime.com`, `4rbanime.fun`) && !PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  redis:
    image: redis:7-alpine
    networks:
      - web

networks:
  web:
    external: true