version: "3.9"

services:
  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_URL: https://4rabanime.fun
    env_file:
      - .env.production
    expose:
      - "3000"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.app.rule=Host(`4rabanime.com`, `4rbanime.fun`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: redis://redis:6379
      CORS_DOMAIN: "https://4rabanime.com,https://4rbanime.fun"
    expose:
      - "4040"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"

      # —— CORS middleware ——
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Methods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Headers=Origin,Accept,Content-Type,Authorization"
      - "traefik.http.middlewares.proxy-cors.headers.customresponseheaders.Access-Control-Allow-Credentials=true"

      # —— Path stripping middleware ——
      - "traefik.http.middlewares.strip-proxy.stripprefix.prefixes=/m3u8-proxy"

      # 🔒 HTTPS route for m3u8-proxy
      - "traefik.http.routers.proxy.rule=Host(`4rabanime.com`,`4rbanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.middlewares=strip-proxy,proxy-cors"
      - "traefik.http.services.proxy.loadbalancer.server.port=4040"

      # HTTP ➜ HTTPS redirect
      - "traefik.http.routers.proxy-http.rule=Host(`4rabanime.com`,`4rbanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy-http.entrypoints=web"
      - "traefik.http.routers.proxy-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

  redis:
    image: redis:7-alpine
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
