# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

# Install tools
RUN apk add --no-cache git openssh-client && \
    corepack disable

# Copy manifests & install all deps including dev
COPY package.json package-lock.json ./
RUN npm ci

# Copy source
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]