version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    expose:
      - "3000"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`4rbanime.fun`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: redis://redis:6379
      CORS_DOMAIN: "https://4rabanime.fun,https://4rabanime.com"
    expose:
      - "4040"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.proxy.rule=Host(`4rabanime.fun`) && PathPrefix(`/m3u8-proxy`)"
      - "traefik.http.routers.proxy.entrypoints=websecure"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.services.proxy.loadbalancer.server.port=4040"
      - "traefik.http.middlewares.strip-proxy.stripprefix.prefixes=/m3u8-proxy"
      - "traefik.http.routers.proxy.middlewares=strip-proxy"

  redis:
    image: redis:7-alpine
    networks:
      - web

networks:
  web:
    external: true
