version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: 4rb-anime/4rb-anime:latest
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_PROXY_URL: http://localhost:4040
      REDIS_URL: redis://redis:6379
      PROXY_INTERNAL_URL: http://proxy:4040
    depends_on:
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.4rb-anime.rule=Host(`4rbanime.com`,`www.4rbanime.com`,`4rbanime.fun`,`www.4rbanime.fun`)"
      - "traefik.http.services.4rb-anime.loadbalancer.server.port=3000"

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    ports:
      - "4040:4040"
    environment:
      PORT: 4040
      CORS_DOMAIN: "localhost:3000,4rb-anime"

volumes:
  redis_data: