version: "3.9"

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - web

  proxy:
    image: dovakiin0/proxy-m3u8:latest
    environment:
      PORT: 4040
      REDIS_URL: redis://redis:6379
      CORS_DOMAIN: "https://4rabanime.com,https://4rbanime.fun,http://localhost"
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "4040"
    networks:
      - web

  4rb-anime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_PROXY_URL=/m3u8-proxy
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - web

volumes:
  redis_data: {}

networks:
  web:
    driver: bridge
